name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          # Change directory to where the Dockerfile is located
          cd server
          # Build the Docker image
          docker build -t ${{ secrets.DOCKER_USERNAME }}/send0-server:send0-server-1 .

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store your Docker Hub username in Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store your Docker Hub password in Secrets

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/send0-server:send0-server-1

      # Step 6: SSH to EC2 and deploy the new image
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }} # Your EC2 instance IP
          username: ubuntu # Change if your user is different
          key: ${{ secrets.EC2_SSH_KEY }} # SSH private key stored in Secrets
          script: |
            # Stop any existing container with the same name
            sudo docker stop send0-server || true
            sudo docker rm send0-server || true

            # Pull the new Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/send0-server:send0-server-1

            # Run the new Docker container with environment variables
            sudo docker run -d \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e AWS_REGION="${{ secrets.AWS_REGION }}" \
              -e AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -p 6000:6000 \
              --name send0-server \
              ${{ secrets.DOCKER_USERNAME }}/send0-server:send0-server-1
